export default [
  {
    id: 1,
    title: "World of Wizard",
    description:
      "You play a wizard who has dwelled into the territory of Houldor, You have to defeat various monsters in order to survive!",
    published: "Sep 21, 2023",
    img: "worldofwizard.png",
    github: "https://github.com/Maniixer/Rpg-dice-game",
    link: "https://wizard-vs-orc.netlify.app",
    language: ["javascript.svg"],
  },
  {
    id: 2,
    title: "War Card Game",
    description:
      "Play a game of war! Take your deck, Each round you draw one card whoever got the highest card win a point until all the cards are drawn, the one with most points win the game!",
    published: "Oct 13, 2023",
    img: "warcard.png",
    github: "https://github.com/Maniixer/War-Card-Game",
    link: "https://warcard.netlify.app",
    language: ["react.svg", "vite.svg"],
  },
  {
    id: 3,
    title: "Airbnb Clone",
    description: "This project was made in Scrimba to learn how to use components, props, data and mapping over objects",
    published: "Oct 27, 2023",
    img: "airbnb.png",
    github: "https://github.com/Maniixer/AirBnb-clone",
    link: "https://mybnbclone.netlify.app/",
    language: ["react.svg", "vite.svg"],
  },
  {
    id: 4,
    title: "The memer",
    description: "Generate random memes and add top and bottom text to the image.",
    published: "Nov 20, 2023",
    img: "thememer.png",
    github: "https://github.com/Maniixer/Meme-generator",
    link: "https://thememer.netlify.app/",
    language: ["react.svg", "vite.svg"],
  },
  {
    id: 5,
    title: "Color scheme",
    description: "Use the color wheel and pick out a scheme to get different hex values!  ",
    published: "Sep 21, 2023",
    img: "colorscheme.png",
    github: "https://github.com/Maniixer/Color-Scheme-Generator",
    link: "https://mycolorscheme.netlify.app/",
    language: ["javascript.svg"],
  },
];
