export default [
  {
    id: 1,
    title: "Floraison",
    description:
      "Developed and designed webshop, maintained product logistic and customer support, Made advertisements on social media platforms.",
    published: "Sep 21, 2021",
    img: "floraison.png",
    github: "",
    link: "https://floraison.bio/",
    language: ["shopify.svg"],
  },
  {
    id: 2,
    title: "FollowYourLegend",
    description: "Developed custom shopify pages, designed product cards and stickers",
    published: "Sep 21, 2021",
    img: "followyourlegend.png",
    github: "",
    link: "https://followyourlegend.com/",
    language: ["shopify.svg"],
  },
  {
    id: 3,
    title: "World of Wizard",
    description:
      "You play a wizard who has dwelled into the territory of Houldor, You have to defeat various monsters in order to survive!",
    published: "Sep 21, 2023",
    img: "worldofwizard.png",
    github: "https://github.com/Maniixer/Rpg-dice-game",
    link: "https://wizard-vs-orc.netlify.app",
    language: ["javascript.svg"],
  },
  {
    id: 4,
    title: "War Card Game",
    description: "Play a game of war! Win by drawing higher cards then your opponent.",
    published: "Oct 13, 2023",
    img: "warcard.png",
    github: "https://github.com/Maniixer/War-Card-Game",
    link: "https://warcard.netlify.app",
    language: ["react.svg", "vite.svg"],
  },

  {
    id: 5,
    title: "The memer",
    description: "Generate random memes and add top and bottom text to the image.",
    published: "Nov 20, 2023",
    img: "thememer.png",
    github: "https://github.com/Maniixer/Meme-generator",
    link: "https://thememer.netlify.app/",
    language: ["react.svg", "vite.svg"],
  },
  {
    id: 6,
    title: "Color scheme",
    description: "Use the color wheel and pick out a scheme to get different hex values!  ",
    published: "Sep 21, 2023",
    img: "colorscheme.png",
    github: "https://github.com/Maniixer/Color-Scheme-Generator",
    link: "https://mycolorscheme.netlify.app/",
    language: ["javascript.svg"],
  },
];
